# Generated by Django 4.0 on 2022-07-02 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommapp', '0005_product_display_product_performane_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='Battery',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='Camera',
            field=models.TextField(blank=True, null=True),
        ),
    ]
