# Generated by Django 4.0 on 2022-07-02 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommapp', '0006_product_battery_product_camera'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='performane',
            new_name='performance',
        ),
    ]
